### ISSUE TITLE
Updating an previously published Process is not possible

### ISSUE THREAD

**Issue by dziegenh** [richwps/semanticproxy#1]
When trying to update a previously published process, the SPClient method updateProcess() throws an InternalSPException. E.g. "SemanticProxy returned 500 for PUT to http://localhost:4567/semanticproxy/resources/process/1418721059839 Error: No such process".
Interesting: the postProcess() method will tell the process already exists.

**Comment by fxbensmann** [comment]
Natural behaviour of a REST interface, update must be sent to the URL of the original resource.
postProcess() refuses to create the resource new because a process with the same WPS and process identifier already exists.

Please keep track of the URL; Also, I might implement a lookup service in the near future.

**Comment by fxbensmann** [comment]
Fixed with lookup service.
